### ISSUE TITLE
fix saving rules

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#84] opened 2020-05-10 23:10 UTC
![wtf](https://user-images.githubusercontent.com/51034573/81512855-40978900-9324-11ea-8045-b80e0a91f163.gif)

**Comment by pinnouse** [comment] 2020-05-11 08:37
Unclear what the bug is. Pls explain

**Comment by BONBONauzWURST** [comment] 2020-05-12 11:20
1) i guess this list is saved rules so users should be able to save them at the name they want
2) if you save rule and later change requirement it change name itself what is not exactly bug but its weird since you can accidentally change rule and it will be hard to find it again if u make a lot of rules 

3) if rule is save it don't remember any settings (you can see name is level but requirements are age equal to 0 where should be level grater than 70)
![image](https://user-images.githubusercontent.com/51034573/81680716-d67e0180-9453-11ea-998a-8259316f3ab7.png)

**Comment by pinnouse** [comment] 2020-05-17 23:58
Since they're not named in DB I've just used the indices to indicate which rule you're working on.
If there's a more elegant solution please reach out to me, but I'm going to close this for now since I can't seem to reproduce any of the bugs myself.

**Closed by pinnouse** 2020-05-17 23:58 UTC
Labels: bug
